//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_CDEV_Guilde_Des_Heros
{
    using System;
    using System.Collections.Generic;
    
    public partial class hero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hero()
        {
            this.objet = new HashSet<objet>();
        }
    
        public int her_id { get; set; }
        public string her_nom { get; set; }
        public string her_prenom { get; set; }
        public string her_specialite { get; set; }
        public string her_classe { get; set; }
        public Nullable<int> her_level { get; set; }
        public Nullable<int> her_puissance { get; set; }
        public Nullable<int> her_nb_mission { get; set; }
        public Nullable<int> her_reputation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<objet> objet { get; set; }
    }
}
